### ISSUE TITLE
IUnknown — `Compile error: User-defined type not defined`

### ISSUE THREAD

**Issue by binajmen** [cristianbuse/VBA-FastDictionary#3]
Hi,

In the process to make external calls to an API. The examples I found use Dictionary. I import your file/class in VBE but get the following error:

![Screenshot 2024-04-29 at 18 30 54](https://github.com/cristianbuse/VBA-FastDictionary/assets/15611419/8ef5dd78-b455-4d01-bd8a-e71cc46a4878)

I'd greatly appreciate your help!

**Comment by cristianbuse** [comment]
Hi @binajmen 

Thank you for your feedback!

Can you please provide more information?
- Are you using Windows or Mac operating system?
- What Application are you importing into? Is it Excel, AutoCad, something else?
- If using a Microsoft Office app, then are you using Office 365 or a specific version of a standalone app?
- Finally, do you have 'stdole' as a project reference?

**Comment by cristianbuse** [comment]
Hi @binajmen ,

Any updates on this one?

**Comment by binajmen** [comment]
Hi @cristianbuse

> Are you using Windows or Mac operating system?

Yes — most probably the issue here

> What Application are you importing into? Is it Excel, AutoCad, something else?

Excel. I would like to perform a POST request on our API server to push some data. And why not pull data with a GET if we manage to make it work.

> If using a Microsoft Office app, then are you using Office 365 or a specific version of a standalone app?

Standalone app.
```
Microsoft® Excel for Mac.
Version 16.84 (24041420).
Licence: Office Home & Student 2021
```

> Finally, do you have OLE Automation as a project reference?

I was not. It is activated now and the original issue is gone.

<img width="519" alt="Screenshot 2024-05-02 at 19 20 42" src="https://github.com/cristianbuse/VBA-FastDictionary/assets/15611419/750a8397-7e1c-4bd5-a290-8ea6498c439c">

Thank you for the guidelines!

I have to find a working example of a POST request now!

**Comment by cristianbuse** [comment]
Thanks @binajmen for your feedback!

Interesting. I found that the ```OLE Automation``` reference is always on by default. However, I never tested on your version of Excel for Mac. Maybe I should add a note for Mac users.

I never did a POST request from a Mac via VBA. On Windows it's fairly easy by using an ```XMLHTTP``` object, but I don't think that library (MSXML) is available on Mac.

**Comment by binajmen** [comment]
> I found that the OLE Automation reference is always on by default.

Perhaps I disabled it while trying a lot of things some days ago. But an additional note would not hurt.

> On Windows it's fairly easy by using an XMLHTTP object, but I don't think that library (MSXML) is available on Mac.

Thank you for the pointers, I will search more on the subject.
